name: Python ci

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs:
 test:
  name: Run python tests
  runs-on: ubantu-latest

steps:
  -name: checkout Repository
   uses: actions/checkout@v3

  -name: Set up Python
   uses: action/setup-python@v4
   with:
    python-version: "3.18"

  -name: install Dependencies
   run: 
    python -m pip install --upgrade pip
    pip install -r requirements.txt

 -name: Run Tests
  run: pytest
